### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by kouroshshafi** [coekie/flowtracker#1]
Is it possible to run this as a chrome extension? I wish this was one of the features of chrome devtools.

**Comment by BitesizedLion** [comment]
No that would not work as this is for Java.

Most browsers and sites use Javascript, not Java and they are not the same thing.

**Comment by coekie** [comment]
FlowTracker only works on the JVM, so only for Java (or other JVM) languages. So it does not work for a browser like Chrome. (Javascript is not Java).
